# Generated by Django 5.2.7 on 2025-11-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableqrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
