# Generated by Django 5.2.7 on 2025-11-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
